version: '3.8'

name: ARLI

services:
  web:
    container_name: arli-py
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../src:/app/src
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=your_secret_key
      - ALLOWED_HOSTS=localhost,127.0.0.1,[::1]
      - DB_NAME=agentic_rag
      - DB_USER=postgres
      - DB_PASSWORD=postgrespassword
      - DB_HOST=db
      - DB_PORT=5432
      - DJANGO_SETTINGS_MODULE=core.settings
    env_file:
      - ../.env
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: arli-db
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=agentic_rag
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespassword
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d agentic_rag"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    name: arli-postgres-data